# Generated by Django 4.2.7 on 2023-11-21 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_car_video_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='main_photo',
        ),
        migrations.RemoveField(
            model_name='carphoto',
            name='photo',
        ),
    ]
