# Generated by Django 4.2.7 on 2023-11-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_carsold'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhotoSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.TextField(default='https://cdn.dealeraccelerate.com/worldwide/1/8226/510832/1920x1440/w/1986-mercedes-benz-560sl')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.carsold')),
            ],
        ),
    ]
